config/routes.rb
Rails.application.routes.draw do
  resources :diaries do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only:[:show, :edit, :update, :destroy]
  def index
    @diarys = Diary.all
  end
  def new
    @diary = Diary.new
  end
  def create
    @diary = Diary.new(diary_params)
    if params[:back]
      render :new
    else
      if @diary.save
        redirect_to diaries_path,notice: "つぶやきました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @diary.update(diary_params)
      redirect_to diaries_path, notice:"編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @diary.destroy
    redirect_to diaries_path,notice:"つぶやきを削除しました。"
  end
  def confirm
    @diary = Diary.new(diary_params)
    render :new if @diary.invalid?
  end
  private
  def diary_params
    params.require(:diary).permit(:content)
  end
  def set_diary
    @diary = Diary.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_diaries_path
    elsif action_name == 'edit'
      diary_path
    end
  end
end

app/views/diaries/_form.html.erb
<%= form_with(model:@diary, local: true, url: choose_new_or_edit )do|form| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2 class="alert alert-danger"><%= @diary.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="diary_title">
    <%= form.label :content %>
    <br>
    <%= form.text_field :content %>
    <%= form.submit %>
  </div>
<% end %>
<br>
<%= link_to 'トップへ戻る',diaries_path, class: "btn btn-primary btn-lg"%>

app/views/diaries/confirm.html.erb
<h3>以下の内容で投稿する。</h3>
<%= form_with(model: @diary, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p><%= @diary.content %></p>
  <%= form.submit  "投稿" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/diaries/edit.html.erb
<h2>つぶやきを編集する</h2>
<%= render 'form' %>

app/views/diaries/index.html.erb
<div class="container">
  <h2>つぶやき一覧</h2>
  <p class="label label-primary"><%= notice %></p>
  <div class="contents">
    <table>
      <% @diarys.each do |diary| %>
        <div class="dialies_list">
          <label><%= diary.content %></label>
          <br>
          <div class="diaries_link">
            <%= link_to '詳細', diary_path(diary.id)%>
            <%= link_to '編集', edit_diary_path(diary.id) %>
            <%= link_to '削除', diary_path(diary.id), method: :delete,data: {confirm: '本当に削除しますか？'} %>
          </div>
        </div>
      <% end %>
    </table>
  </div>
  <br>
  <%= link_to 'つぶやく', new_diary_path,class:"btn btn-primary btn-lg" %>
</div>

app/views/diaries/new.html.erb
<%= render 'form' %>

app/views/diaries/show.html.erb
<h2>詳細</h2>
<br>
<p>つぶやき: <%= @diary.content %></p>
<br>
<%= link_to 'トップへ戻る',diaries_path,class:"btn btn-primary btn-lg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>今日もつぶやき</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">今日もつぶやき</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://localhost:3000/diaries">今日もつぶやき</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="footer">
        <p>運営会社 TSUBUYAKI株式会社</p>
        <p>© 2015-2020 TSUBUYAKI Corp.</p>
      </div>
    </footer>
  </body>
</html>